openapi: 3.0.0
info:
  title: Startups API
  description: API to manage a list of startups ðŸš€
  version: 1.0.0

servers:
  - url: https://startup-api-6pkn.onrender.com/api
    description: Startup-Api

tags:
  - name: Startups
    description: Startup management

paths:
  /startups:
    get:
      summary: List all startups
      tags: [Startups]
      responses:
        200:
          description: List of startups returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Startup'
        500:
          description: Internal server error
    post:
      summary: Create a new startup
      tags: [Startups]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Startup'
      responses:
        201:
          description: Startup created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Startup'
        400:
          description: Invalid request (missing or incorrect data)
        500:
          description: Internal server error

components:
  schemas:
    Startup:
      type: object
      required:
        - name
        - founder
        - description
        - yearCreated
      properties:
        name:
          type: string
          description: Name of the startup
          example: SpaceX
        founder:
          type: string
          description: Founderâ€™s name
          example: Elon Musk
        description:
          type: string
          description: Brief description of the startup
          example: Aerospace company developing rockets and spacecraft
        yearCreated:
          type: integer
          description: Year of creation
          example: 2002
